### PR TITLE
Add issue templates and Makefile target for generating them

### PR DESCRIPTION
**Pull request by caufieldjh**
Borrowing extensively from @cthoyt and https://github.com/biopragmatics/bioregistry to assemble templates, scripts, and GH Action for creating new PRs when new data instances are requested.

### CODE REVIEW

**Comment by cthoyt** [comment]
@caufieldjh amazing! borrow away. Do you think there is a core set of utilities that would be useful to externalize into their own package?

**Comment by caufieldjh** [comment]
> Do you think there is a core set of utilities that would be useful to externalize into their own package?

I'm sure there is! Even for LinkML alone it would be convenient to have a consistent set of PR automation scripts, though I can imagine that becoming a bit of a rabbit hole depending on what a PR may need to do beyond writing to the end of a file. Minimal functionality would probably look something like "if issue with a certain tag is opened, create a new branch and placeholder PR"

**Comment by caufieldjh** [comment]
Really much of this would be a nice module: https://github.com/biopragmatics/bioregistry/tree/main/src/bioregistry/gh

**Comment by caufieldjh** [comment]
Going to merge this in order to test it with some live issues. For now, it will only work with the main Standards Registry set (`DataStandardOrTool.yaml`) but there should be a straightforward way to determine which other file should be updated based on the submitted issue.

**Comment by cthoyt** [comment]
@caufieldjh since you did copy licensed code verbatim, I think it would be appropriate to give proper credit inside the code, noting the original license (MIT), the place the code came from, and noting any changes made to it

**Comment by caufieldjh** [comment]
Yes, absolutely - stay tuned

**Comment by caufieldjh** [comment]
@cthoyt see b938f70 and definitely let me know if you'd like to be credited differently!

We don't have a LICENSE set up in this repo yet 🤦, but I'll mention similar material there, too.

**Pull request merged**
