### PR TITLE
feat: add has_ai_application tag to standard collections that have ai…

### PR DESCRIPTION
**Pull request by katiestahl**
… applications

I think this should still be considered a WIP but here's what I've got so far adding this tag. I added it to:

- standards/tools that are associated with ML or neural networks
- things that are (or have) schemas
- things that are data models
- things associated with DICOM
- things associated with AI 
- things associated with standards that B2AI uses

I'd like to open this as a draft for now to allow for discussion on any of these and other types of entities I may have missed! (or that I have included that should not have this tag)

### CODE REVIEW

**Review by caufieldjh — APPROVED** [review]

**Comment by caufieldjh** [comment]
Does `make all` work - and if not, does `poetry run make all` work?

**Comment by katiestahl** [comment]
Here's what I've tried so far to get the `make` to work:
1. I ran into an issue because I didn't have wget installed. Installed that and then it was able to add the schemas
2. The issue I posted in the comment above - division by 0. I tried isolating the following code in a script and call it in the makefile to see what would happen:
```
#!/bin/bash
declare -A CLASSES=(
    ["src/data/DataStandardOrTool.yaml"]="DataStandardOrToolContainer"
    ["src/data/DataSubstrate.yaml"]="DataSubstrateContainer"
    ["src/data/DataTopic.yaml"]="DataTopicContainer"
    ["src/data/Organization.yaml"]="OrganizationContainer"
    ["src/data/UseCase.yaml"]="UseCaseContainer"
)

for key in "${!CLASSES[@]}"; do
    echo $key
    for format in json tsv; do
        echo "Converting $key to $format..."
        newfn="${key##*/}"
        extension="${newfn##*.}"
        newfn="${newfn%.*}.$format"
        newpath="project/data/$newfn"
        poetry run linkml-convert -s src/schema/standards_schema_all.yaml -C "${CLASSES[$key]}" -t "$format" -o "$newpath" "$key"
    done
done
```
then changed the code in `all-data` in my project.Makefile to:
```
all-data:
	@echo "Removing any previously created serializations..."
	rm -rf $(SERIAL_DATA_DIR) ;
	mkdir -p $(SERIAL_DATA_DIR) ;
	@echo "Making serializations with linkml-convert..."
	./convert_data.sh
	$(MAKE_HTML_LINKS)
	$(MAKE_STD_LINKS)
```
3. After doing that and running `make all` I was getting `/bin/bash: mkdocs: command not found`. I installed `mkdocs`
4. After installing mkdocs, with the separated out script, I get:
```
Removing any previously created serializations...
rm -rf project/data/ ;
mkdir -p project/data/ ;
Making serializations with linkml-convert...
./convert_data.sh
./convert_data.sh: line 2: src/data/DataStandardOrTool.yaml: division by 0 (error token is "/DataStandardOrTool.yaml")
find project/data/ -type f -name '*.tsv' -exec sed -i 's/http\S*/<a href="&">&<\/a>/g' {} \;
find project/data/ -type f -name '*.tsv' -exec sed -i -e 's/B2AI_USECASE\S*/\[&\]\(UseCase.markdown\)/g' -e 's/B2AI_ORG\S*/\[&\]\(Organization.markdown\)/g' -e 's/B2AI_TOPIC\S*/\[&\]\(DataTopic.markdown\)/g' -e 's/B2AI_SUBSTRATE\S*/\[&\]\(DataSubstrate.markdown\)/g' -e 's/B2AI_STANDARD\S*/\[&\]\(DataStandardOrTool.markdown\)/g'  {} \;
mkdocs build ;
ERROR   -  Config value 'theme': Unrecognised theme name: 'material'. The available installed themes are: mkdocs, readthedocs

Aborted with a configuration error!
make: *** [site] Error 1
```

I thought maybe I had a weird or old version of make, so I ran `make -v` and get:
```
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
```

This should be compatible. But I've narrowed this down to my shell /really/ not liking the `declare -A` syntax.. I think...

**Comment by katiestahl** [comment]
Going to keep adding comments as I try new things.

Saw this issue on stackoverflow: https://stackoverflow.com/questions/62417989/what-is-the-division-by-0-error-token-is-etc-shadow-error

Switched () to []:
```
#!/bin/bash
declare -A CLASSES=[
    ["src/data/DataStandardOrTool.yaml"]="DataStandardOrToolContainer"
    ["src/data/DataSubstrate.yaml"]="DataSubstrateContainer"
    ["src/data/DataTopic.yaml"]="DataTopicContainer"
    ["src/data/Organization.yaml"]="OrganizationContainer"
    ["src/data/UseCase.yaml"]="UseCaseContainer"
]
```
And now getting:
```
Removing any previously created serializations...
rm -rf project/data/ ;
mkdir -p project/data/ ;
Making serializations with linkml-convert...
./convert_data.sh
./convert_data.sh: line 2: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
./convert_data.sh: line 3: [src/data/DataStandardOrTool.yaml]=DataStandardOrToolContainer: No such file or directory
./convert_data.sh: line 4: [src/data/DataSubstrate.yaml]=DataSubstrateContainer: No such file or directory
./convert_data.sh: line 5: [src/data/DataTopic.yaml]=DataTopicContainer: No such file or directory
./convert_data.sh: line 6: [src/data/Organization.yaml]=OrganizationContainer: No such file or directory
./convert_data.sh: line 7: [src/data/UseCase.yaml]=UseCaseContainer: No such file or directory
./convert_data.sh: line 8: ]: command not found
find project/data/ -type f -name '*.tsv' -exec sed -i 's/http\S*/<a href="&">&<\/a>/g' {} \;
find project/data/ -type f -name '*.tsv' -exec sed -i -e 's/B2AI_USECASE\S*/\[&\]\(UseCase.markdown\)/g' -e 's/B2AI_ORG\S*/\[&\]\(Organization.markdown\)/g' -e 's/B2AI_TOPIC\S*/\[&\]\(DataTopic.markdown\)/g' -e 's/B2AI_SUBSTRATE\S*/\[&\]\(DataSubstrate.markdown\)/g' -e 's/B2AI_STANDARD\S*/\[&\]\(DataStandardOrTool.markdown\)/g'  {} \;
mkdocs build ;
ERROR   -  Config value 'theme': Unrecognised theme name: 'material'. The available installed themes are: mkdocs, readthedocs

Aborted with a configuration error!
make: *** [site] Error 1
```

**Comment by katiestahl** [comment]
omg it was my bash version. The makefile specifies to use `/bin/bash`, which was a version prior to 4.0 (which introduced associative arrays). I had to change this line in `project.Makefile`:
`SHELL=/bin/bash` to `SHELL=/opt/homebrew/bin/bash`

**Pull request merged**
